[tool.poetry]
name = "movie-database"
version = "0.1.0"
description = ""
authors = ["Egor <baseddepartmentzx77@gmail.com>"]
readme = "README.md"
packages = [{include = "movie_database"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.api.dependencies]
fastapi = "^0.97.0"
uvicorn = "^0.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
