[tool.poetry]
name = "movie-database"
version = "0.1.0"
description = ""
authors = ["Egor <baseddepartmentzx77@gmail.com>"]
readme = "README.md"
packages = [{include = "movie_database"}]

[tool.poetry.dependencies]
python = "^3.10"
psycopg2-binary = "^2.9.6"
python-jose = "^3.3.0"


[tool.poetry.group.api.dependencies]
fastapi = "^0.97.0"
uvicorn = "^0.22.0"


[tool.poetry.group.tests.dependencies]
pytest = "^7.3.2"


[tool.poetry.group.telegram.dependencies]
aiogram = "^3.0.0b5"


[tool.poetry.group.cli.dependencies]
typer = {extras = ["all"], version = "^0.9.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
